
import type { ProductListing } from '@/types';

export const dummyProducts: ProductListing[] = [
  // Electronics
  {
    id: 'prod-elec-1',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in sound with these premium noise-cancelling headphones. Long battery life and comfortable design.',
    price: 8999,
    originalPrice: 12999,
    categoryIds: ['cat-electronics'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?headphones,wireless',
    imageAiHint: 'headphones wireless',
    brand: 'TechAudio',
    rating: 4.7,
    reviewCount: 1250,
    stock: 50,
    tags: ['audio', 'headphones', 'noise-cancelling'],
  },
  {
    id: 'prod-elec-2',
    name: 'Smartwatch Series X',
    description: 'Track your fitness, receive notifications, and more with this sleek smartwatch. Multiple watch faces and bands available.',
    price: 14999,
    categoryIds: ['cat-electronics'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?smartwatch,wearable',
    imageAiHint: 'smartwatch wearable',
    brand: 'ConnectWear',
    rating: 4.5,
    reviewCount: 890,
    stock: 30,
    tags: ['smartwatch', 'fitness', 'wearable'],
  },
  // Fashion
  {
    id: 'prod-fashion-1',
    name: 'Men\'s Classic Cotton T-Shirt',
    description: 'Comfortable and stylish 100% cotton t-shirt, perfect for everyday wear. Available in various colors.',
    price: 799,
    categoryIds: ['cat-fashion'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?mens,tshirt,cotton',
    imageAiHint: 'mens tshirt cotton',
    brand: 'UrbanStyle',
    rating: 4.3,
    reviewCount: 500,
    stock: 100,
    tags: ['men', 't-shirt', 'apparel'],
    variants: [
      { id: 'v-color', name: 'Color', options: [{ value: 'Black' }, { value: 'White' }, { value: 'Navy Blue' }] },
      { id: 'v-size', name: 'Size', options: [{ value: 'S' }, { value: 'M' }, { value: 'L' }, { value: 'XL' }] },
    ],
  },
  {
    id: 'prod-fashion-2',
    name: 'Women\'s Floral Print Summer Dress',
    description: 'Light and airy summer dress with a beautiful floral print. Ideal for casual outings or beach days.',
    price: 1899,
    categoryIds: ['cat-fashion'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?womens,dress,floral',
    imageAiHint: 'womens dress floral',
    brand: 'BellaChic',
    rating: 4.6,
    reviewCount: 350,
    stock: 60,
    tags: ['women', 'dress', 'summer'],
  },
  // Home & Kitchen
  {
    id: 'prod-home-1',
    name: 'Stainless Steel Cookware Set (10-Piece)',
    description: 'Durable and versatile 10-piece stainless steel cookware set. Includes pots, pans, and lids.',
    price: 5999,
    categoryIds: ['cat-home-kitchen'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?cookware,set,stainless,steel',
    imageAiHint: 'cookware set stainless steel',
    brand: 'KitchenPro',
    rating: 4.8,
    reviewCount: 600,
    stock: 40,
    tags: ['kitchen', 'cookware', 'utensils'],
  },
  // Books
  {
    id: 'prod-books-1',
    name: 'The Midnight Library by Matt Haig',
    description: 'A captivating novel about choices, regrets, and the infinite possibilities of life.',
    price: 450,
    categoryIds: ['cat-books'],
    imageUrl: 'https://source.unsplash.com/random/600x600/?book,cover,novel',
    imageAiHint: 'book cover novel',
    brand: 'Penguin Books',
    rating: 4.9,
    reviewCount: 2500,
    stock: 70,
    tags: ['fiction', 'contemporary', 'fantasy'],
  },
];

    