
import type { Restaurant } from '@/types';

export const dummyRestaurants: Restaurant[] = [
  {
    id: 'resto-1',
    name: 'Nandhana Palace',
    cuisine: 'Andhra, Biryani',
    rating: 4.5,
    deliveryTime: '30-40 min',
    priceRange: '₹₹',
    imageUrl: 'https://source.unsplash.com/random/800x600/?indian,restaurant,food',
    imageAiHint: 'indian restaurant food',
    address: '123, Koramangala 5th Block, Bangalore',
    menu: [
      { id: 'm1-1', name: 'Chicken Biryani', category: 'Main Course', price: 350, description: 'Aromatic basmati rice cooked with succulent chicken pieces and traditional spices.', imageUrl: 'https://source.unsplash.com/random/400x300/?chicken,biryani', imageAiHint: 'chicken biryani' },
      { id: 'm1-2', name: 'Paneer Butter Masala', category: 'Main Course', price: 280, description: 'Soft paneer cubes cooked in a rich and creamy tomato-based gravy.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?paneer,butter,masala', imageAiHint: 'paneer butter masala' },
      { id: 'm1-3', name: 'Gobi Manchurian', category: 'Appetizers', price: 220, description: 'Crispy cauliflower florets tossed in a tangy and spicy Manchurian sauce.', isVegetarian: true, isSpicy: true, imageUrl: 'https://source.unsplash.com/random/400x300/?gobi,manchurian', imageAiHint: 'gobi manchurian' },
      { id: 'm1-4', name: 'Gulab Jamun', category: 'Desserts', price: 150, description: 'Soft, spongy milk-solid balls soaked in sweet syrup.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?gulab,jamun', imageAiHint: 'gulab jamun' },
      { id: 'm1-5', name: 'Masala Papad', category: 'Appetizers', price: 80, description: 'Crispy papad topped with chopped onions, tomatoes, and spices.', isVegetarian: true, isSpicy: true, imageUrl: 'https://source.unsplash.com/random/400x300/?masala,papad', imageAiHint: 'masala papad' },
    ],
  },
  {
    id: 'resto-2',
    name: "Luigi's Italian Kitchen",
    cuisine: 'Italian, Pizza',
    rating: 4.2,
    deliveryTime: '40-50 min',
    priceRange: '₹₹₹',
    imageUrl: 'https://source.unsplash.com/random/800x600/?italian,pizzeria,interior',
    imageAiHint: 'italian pizzeria interior',
    address: '45, Indiranagar 100 Feet Road, Bangalore',
    menu: [
      { id: 'm2-1', name: 'Margherita Pizza', category: 'Pizza', price: 450, description: 'Classic pizza with tomato, mozzarella, and basil.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?margherita,pizza', imageAiHint: 'margherita pizza' },
      { id: 'm2-2', name: 'Pasta Carbonara', category: 'Pasta', price: 520, description: 'Spaghetti with eggs, Pecorino Romano cheese, pancetta, and black pepper.', imageUrl: 'https://source.unsplash.com/random/400x300/?pasta,carbonara', imageAiHint: 'pasta carbonara' },
      { id: 'm2-3', name: 'Bruschetta', category: 'Appetizers', price: 300, description: 'Grilled bread rubbed with garlic and topped with olive oil, salt, and tomato.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?bruschetta', imageAiHint: 'bruschetta' },
      { id: 'm2-4', name: 'Tiramisu', category: 'Desserts', price: 350, description: 'Coffee-flavoured Italian dessert.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?tiramisu', imageAiHint: 'tiramisu' },
      { id: 'm2-5', name: 'Pepperoni Pizza', category: 'Pizza', price: 550, description: 'Classic pizza with spicy pepperoni slices.', imageUrl: 'https://source.unsplash.com/random/400x300/?pepperoni,pizza', imageAiHint: 'pepperoni pizza' },
    ],
  },
  {
    id: 'resto-3',
    name: 'Dragon Wok',
    cuisine: 'Chinese, Asian',
    rating: 4.0,
    deliveryTime: '25-35 min',
    priceRange: '₹₹',
    imageUrl: 'https://source.unsplash.com/random/800x600/?chinese,restaurant,decor',
    imageAiHint: 'chinese restaurant decor',
    address: '77, Commercial Street, Bangalore',
    menu: [
      { id: 'm3-1', name: 'Chicken Hakka Noodles', category: 'Noodles & Rice', price: 280, description: 'Stir-fried noodles with chicken and vegetables.', imageUrl: 'https://source.unsplash.com/random/400x300/?hakka,noodles', imageAiHint: 'hakka noodles' },
      { id: 'm3-2', name: 'Veg Spring Rolls', category: 'Appetizers', price: 180, description: 'Crispy fried rolls stuffed with mixed vegetables.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?spring,rolls', imageAiHint: 'spring rolls' },
      { id: 'm3-3', name: 'Schezwan Fried Rice', category: 'Noodles & Rice', price: 300, description: 'Spicy fried rice tossed with Schezwan sauce and vegetables.', isVegetarian: true, isSpicy: true, imageUrl: 'https://source.unsplash.com/random/400x300/?fried,rice', imageAiHint: 'fried rice' },
      { id: 'm3-4', name: 'Honey Chilli Potato', category: 'Appetizers', price: 200, description: 'Crispy fried potato strips tossed in a sweet and spicy honey chilli sauce.', isVegetarian: true, isSpicy: true, imageUrl: 'https://source.unsplash.com/random/400x300/?honey,chilli,potato', imageAiHint: 'honey chilli potato' },
    ],
  },
  {
    id: 'resto-4',
    name: 'Healthy Bites Salad Bar',
    cuisine: 'Salads, Healthy',
    rating: 4.8,
    deliveryTime: '20-30 min',
    priceRange: '₹',
    imageUrl: 'https://source.unsplash.com/random/800x600/?salad,bar,healthy',
    imageAiHint: 'salad bar healthy',
    address: 'Unit 10, HSR Layout, Bangalore',
    menu: [
      { id: 'm4-1', name: 'Quinoa Power Bowl', category: 'Salads', price: 320, description: 'Quinoa, mixed greens, roasted vegetables, chickpeas, and a lemon-tahini dressing.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?quinoa,salad', imageAiHint: 'quinoa salad' },
      { id: 'm4-2', name: 'Grilled Chicken Caesar Salad', category: 'Salads', price: 350, description: 'Romaine lettuce, grilled chicken, croutons, parmesan cheese, and Caesar dressing.', imageUrl: 'https://source.unsplash.com/random/400x300/?caesar,salad', imageAiHint: 'caesar salad' },
      { id: 'm4-3', name: 'Fresh Fruit Platter', category: 'Healthy Sides', price: 250, description: 'Assortment of seasonal fresh fruits.', isVegetarian: true, imageUrl: 'https://source.unsplash.com/random/400x300/?fruit,platter', imageAiHint: 'fruit platter' },
    ],
  },
];
