type User @table {
  displayName: String!
  email: String
  photoUrl: String
  bio: String
  createdAt: Timestamp!
}

type Business @table {
  name: String!
  description: String!
  location: String!
  contactInformation: String!
  businessCategory: String
  createdAt: Timestamp!
  owner: User!
}

type Skill @table {
  name: String!
  description: String
  proficiency: String!
  createdAt: Timestamp!
  user: User!
}

type Vehicle @table {
  make: String!
  model: String!
  year: Int!
  licensePlate: String!
  description: String
  createdAt: Timestamp!
  owner: User!
}

type Service @table {
  available: Boolean!
  hourlyRate: Float
  description: String
  createdAt: Timestamp!
  provider: User!
  skill: Skill!
}

type SearchQuery @table {
  searchTerm: String!
  createdAt: Timestamp!
  user: User!
}
